//
//  ConstantFile.h
//  iPlan
//
//  Created by Yingbo Zhan on 11-6-18.
//  Copyright 2011 NUS. All rights reserved.
//



#define LANG_CHINESE @"Chinese"
#define FREQUENCY_INVALID 0
#define MODULE_DOCUMENT_NAME @"Modules"

// Module Class Types
#define MODULE_CLASS_TYPE_LECTURE @"LECTURE"
#define MODULE_CLASS_TYPE_DESIGN_LECTURE @"DESIGN LECTURE"
#define MODULE_CLASS_TYPE_LABORATORY @"LABORATORY"
#define MODULE_CLASS_TYPE_SEMINAR_STYLE_MODULE_CLASS @"SEMINAR-STYLE MODULE CLASS"
#define MODULE_CLASS_TYPE_SECTIONAL_TEACHING @"SECTIONAL TEACHING"
#define MODULE_CLASS_TYPE_TUTORIAL @"TUTORIAL"
#define MODULE_CLASS_TYPE_TUTORIAL_TYPE_3 @"TUTORIAL TYPE 3"
#define MODULE_CLASS_TYPE_TUTORIAL_TYPE_2 @"TUTORIAL TYPE 2"
#define MODULE_CLASS_TYPE_PACKAGED_TUTORIAL @"PACKAGED TUTORIAL"

